# Generated by Django 4.2.2 on 2023-08-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsBooked',
            fields=[
                ('email', models.OneToOneField(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.student')),
                ('room_booked', models.CharField(max_length=20)),
                ('date_booked', models.DateTimeField()),
                ('duration_booked', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'roomsbooked',
                'managed': False,
            },
        ),
    ]
