# Generated by Django 4.2.2 on 2023-08-29 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_authuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomsbooked',
            options={'managed': True},
        ),
    ]
