# Generated by Django 4.2.2 on 2023-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_room_options_alter_roomsbooked_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
