# Generated by Django 4.2.2 on 2023-08-30 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_authuser_room_image_room_room_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'managed': False},
        ),
    ]
