# Generated by Django 4.2.2 on 2023-08-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomsbooked',
            table=None,
        ),
    ]
