# Generated by Django 4.2.2 on 2023-08-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_roomsbooked_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomsbooked',
            table='roomsbooked',
        ),
    ]
