# Generated by Django 4.2.2 on 2023-08-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_roomsbooked_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomsbooked',
            options={},
        ),
    ]
